vich_uploader:
    db_driver: orm

    mappings:
        article_picture:
            uri_prefix: /media/articles
            upload_destination: '%kernel.project_dir%/public/media/articles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
