<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIVqXwq5\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIVqXwq5/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerIVqXwq5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerIVqXwq5\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerIVqXwq5\srcApp_KernelProdContainer([
    'container.build_hash' => 'IVqXwq5',
    'container.build_id' => '6bf5eaf1',
    'container.build_time' => 1651812789,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIVqXwq5');
