#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home :
    path: /
    controller: App\Controller\HomeController::index

# article.index :
#     path: /articles
#     controller: App\Controller\ArticleController::index