<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDfn3AET\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDfn3AET/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDfn3AET.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDfn3AET\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDfn3AET\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Dfn3AET',
    'container.build_id' => '88e26a8c',
    'container.build_time' => 1651829162,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDfn3AET');
